name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: ~

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.6', '2.7', '3.0', '3.1', '3.2']
        bundle-gemfile: ['Gemfile', 'Gemfile.sidekiq-5', 'Gemfile.sidekiq-6', 'Gemfile.sidekiq-6-0', 'Gemfile.sidekiq-7']
        exclude:
          # Sidekiq 7+ is ruby 2.7+ only
          - ruby-version: 2.6
            bundle-gemfile: Gemfile.sidekiq-7

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.bundle-gemfile }}
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0

    - name: Run tests
      run: bundle exec rake spec
